// client/src/components/SnapshotModal.jsx
import { useEffect, useMemo } from "react";

export default function SnapshotModal({ open, onClose }) {
  const API_BASE = import.meta.env.VITE_API_BASE_URL || "http://localhost:3001";

  // New timestamp each time modal opens -> bust browser cache
  const cacheBust = useMemo(() => Date.now(), [open]);

  const images = useMemo(
    () => [
      {
        src: `${API_BASE}/snapshots/snapshot_1_geo_distribution.png?v=${cacheBust}`,
        alt: "Snapshot 1 - Geographic Distribution",
      },
      {
        src: `${API_BASE}/snapshots/snapshot_2_country_split.png?v=${cacheBust}`,
        alt: "Snapshot 2 - Country Split",
      },
      {
        src: `${API_BASE}/snapshots/snapshot_3_package_distribution.png?v=${cacheBust}`,
        alt: "Snapshot 3 - Package Distribution",
      },
      {
        src: `${API_BASE}/snapshots/snapshot_4_subscription_status.png?v=${cacheBust}`,
        alt: "Snapshot 4 - Subscription Status",
      },
      {
        src: `${API_BASE}/snapshots/snapshot_5_billing_cycle.png?v=${cacheBust}`,
        alt: "Snapshot 5 - Billing Cycle",
      },
      {
        src: `${API_BASE}/snapshots/snapshot_6_customer_creation_timeline.png?v=${cacheBust}`,
        alt: "Snapshot 6 - Customer Creation Timeline",
      },
    ],
    [API_BASE, cacheBust]
  );

  useEffect(() => {
    if (!open) return;

    const onKey = (e) => {
      if (e.key === "Escape") onClose?.();
    };

    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open, onClose]);

  if (!open) return null;

  return (
    <div style={styles.backdrop}>
      <div
        style={styles.modal}
        onMouseDown={(e) => {
          e.stopPropagation();
        }}
      >
        <div style={styles.header}>
          <h2 style={{ margin: 0 }}>Snapshots</h2>
          <button onClick={onClose} style={styles.xBtn} aria-label="Close">
            ✕
          </button>
        </div>

        <p style={styles.subtext}>
          Quick visual snapshots generated by the seeder.
        </p>

        <div style={styles.imageGrid}>
          {images.map((img) => (
            <div key={img.src} style={styles.thumbCard}>
              <img
                src={img.src}
                alt={img.alt}
                style={styles.thumbImg}
                onError={(e) => {
                  console.error("Failed to load snapshot:", img.src);
                  e.currentTarget.style.opacity = "0.25";
                }}
              />
              <div style={styles.thumbCaption}>{img.alt}</div>
            </div>
          ))}
        </div>

        <div style={styles.footer}>
          <button onClick={onClose} style={styles.btnSecondary}>
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

const styles = {
  backdrop: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.55)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    zIndex: 9999,
  },
  modal: {
    width: "min(980px, 100%)",
    maxHeight: "90vh",
    overflowY: "auto",
    background: "#0f1115",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: 14,
    padding: 18,
    boxShadow: "0 20px 60px rgba(0,0,0,0.5)",
    color: "white",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  xBtn: {
    background: "transparent",
    border: "none",
    color: "white",
    fontSize: 18,
    cursor: "pointer",
  },
  subtext: {
    marginTop: 10,
    marginBottom: 16,
    opacity: 0.85,
  },
  imageGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 14,
  },
  thumbCard: {
    border: "1px solid rgba(255,255,255,0.12)",
    borderRadius: 12,
    overflow: "hidden",
    background: "rgba(255,255,255,0.04)",
  },
  thumbImg: {
    width: "100%",
    height: 200,
    objectFit: "contain",
    display: "block",
    background: "#000",
  },
  thumbCaption: {
    padding: "8px 10px",
    fontSize: 13,
    opacity: 0.9,
    borderTop: "1px solid rgba(255,255,255,0.08)",
  },
  footer: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 16,
  },
  btnSecondary: {
    padding: "10px 14px",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.15)",
    background: "transparent",
    color: "white",
    cursor: "pointer",
  },
};